#!/usr/bin/env python3
"""
enriched Gemini 결과 + Komoot 원본 데이터 → waypoints INSERT SQL 생성.

- enriched_gemini_progress.json (or enriched_gemini.json): Gemini 결과
- KOMOOT_FULL/*/metadata.json: 이미지, 팁 원본
- unique_pois_with_address.json: 주소 데이터

Output: scripts/output/insert_waypoints.sql

Usage:
    python crawl_data/refine/build_waypoints_sql.py
    python crawl_data/refine/build_waypoints_sql.py --input enriched_gemini.json  # 최종 파일 사용
"""

import os
import sys
import json
import argparse
from pathlib import Path
from collections import defaultdict

SCRIPT_DIR = Path(__file__).parent
CRAWL_DIR = SCRIPT_DIR / ".." / "KOMOOT_FULL"
DEFAULT_INPUT = SCRIPT_DIR / "final_pois_with_fixed_names.json"
OUTPUT_SQL = Path(__file__).parent.parent.parent / "scripts" / "output" / "insert_waypoints.sql"


def load_komoot_extras() -> dict:
    """Komoot 원본에서 이미지/팁 수집. {name → {images, tips, source_ids}}"""
    extras = defaultdict(lambda: {"images": [], "tips": [], "source_ids": set(), "tour_count": 0})

    for d in sorted(os.listdir(CRAWL_DIR)):
        meta_path = CRAWL_DIR / d / "metadata.json"
        if not meta_path.exists():
            continue
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)

        for wp in meta.get("waypoints", []):
            name = wp.get("name", "").strip()
            if not name:
                continue
            entry = extras[name]

            # 이미지
            for img in wp.get("images", []):
                src = img.get("src", "")
                if src and src not in [x for x in entry["images"]]:
                    entry["images"].append(src)

            # 팁
            for tip in wp.get("tips", []):
                text = tip.get("text", "").strip()
                if text and len(text) > 5:
                    tip_entry = {"text": text, "author": tip.get("author", "")}
                    if tip_entry not in entry["tips"]:
                        entry["tips"].append(tip_entry)

            # source tracking
            wp_id = wp.get("id") or wp.get("index")
            if wp_id:
                entry["source_ids"].add(str(wp_id))

    # set → list
    for v in extras.values():
        v["source_ids"] = list(v["source_ids"])

    return dict(extras)


def sql_escape(s: str) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def build_etc_json(poi: dict, komoot_extra: dict) -> dict:
    """waypoints.etc JSONB 구성."""
    etc = {
        "source": "KOMOOT",
    }
    if komoot_extra.get("source_ids"):
        etc["source_ids"] = komoot_extra["source_ids"][:10]
    if komoot_extra.get("images"):
        etc["image_urls"] = komoot_extra["images"][:5]  # 최대 5개
    if komoot_extra.get("tips"):
        etc["tips"] = komoot_extra["tips"][:5]  # 최대 5개
    if poi.get("category"):
        etc["category_raw"] = poi["category"]
    if poi.get("tour_count"):
        etc["tour_count"] = poi["tour_count"]
    if poi.get("nearby_landmarks"):
        etc["nearby_landmarks"] = poi["nearby_landmarks"]
    if poi.get("confidence"):
        etc["confidence"] = poi["confidence"]
    if poi.get("name_correction"):
        etc["name_corrected"] = poi["name_correction"]
    if poi.get("address"):
        etc["address"] = poi["address"]
    return etc


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    args = parser.parse_args()

    # Load enriched data
    with open(args.input, encoding="utf-8") as f:
        pois = json.load(f)
    print(f"입력: {len(pois)}개 POI ({args.input.name})")

    # Load Komoot extras
    print("Komoot 원본 데이터 로딩...")
    komoot_extras = load_komoot_extras()
    matched = sum(1 for p in pois if p["name"] in komoot_extras)
    print(f"  Komoot 매칭: {matched}/{len(pois)}개")

    # Filter: error/pending/discard 제외
    valid_pois = [p for p in pois if p.get("confidence") not in ("error", "pending", "discard", None)]
    print(f"  유효: {len(valid_pois)}개 (error/pending/discard 제외)")

    # Build SQL
    lines = [
        "-- Waypoints INSERT SQL",
        f"-- Source: {args.input.name} ({len(valid_pois)}개)",
        "-- Generated by: python crawl_data/refine/build_waypoints_sql.py",
        "",
        "BEGIN;",
        "",
        "-- 기존 데이터 정리 (재실행 안전)",
        "TRUNCATE waypoints CASCADE;",
        "",
    ]

    for poi in valid_pois:
        # final_name (fix_poi_names_mt 결과) > name_correction > name
        name = poi.get("final_name") or poi.get("name_correction") or poi["name"]

        description = poi.get("description", "")
        lat = poi["lat"]
        lng = poi["lng"]

        # waypoint_type → PostgreSQL array
        wt = poi.get("waypoint_type", ["other"])
        type_array = "'{" + ",".join(wt) + "}'"

        # etc JSONB
        komoot_extra = komoot_extras.get(poi["name"], {"images": [], "tips": [], "source_ids": []})
        etc = build_etc_json(poi, komoot_extra)
        etc_json = json.dumps(etc, ensure_ascii=False).replace("'", "''")

        lines.append(
            f"INSERT INTO waypoints (name, description, type, location, is_verified, etc) VALUES ("
            f"{sql_escape(name[:100])}, "
            f"{sql_escape(description)}, "
            f"{type_array}::waypoint_type[], "
            f"ST_SetSRID(ST_MakePoint({lng}, {lat}), 4326), "
            f"false, "
            f"'{etc_json}'::jsonb"
            f");"
        )

    lines.extend(["", "COMMIT;", ""])

    # Write SQL
    OUTPUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_SQL, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n→ {OUTPUT_SQL} ({len(valid_pois)}개 INSERT)")


if __name__ == "__main__":
    main()
