#!/usr/bin/env python3
"""
자동 태그/설명 생성 테스트 + DB insert용 출력 생성.

Usage:
    python scripts/test_auto_tag.py 283              # 단일 루트
    python scripts/test_auto_tag.py 283 280 282      # 복수 루트
    python scripts/test_auto_tag.py --apply 283      # 생성 후 DB에 바로 적용
"""

import os
import sys
import json

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'backend'))

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '..', 'backend', '.env'))

import psycopg2
from psycopg2.extras import RealDictCursor
from app.services.auto_tag_service import (
    generate_tags_and_description,
    get_existing_tags,
    _build_route_line_wkt,
    _get_waypoints_along_route,
    _extract_control_points,
    _get_waypoints_near_control_points,
)

DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": int(os.getenv("DB_PORT", 5432)),
    "dbname": os.getenv("DB_NAME", "postgres"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", ""),
}

STORAGE_DIR = os.path.join(os.path.dirname(__file__), '..', 'backend', 'storage')


def process_route(conn, route_id: int) -> dict | None:
    cur = conn.cursor()

    cur.execute("""
        SELECT id, uuid, title, description, data_file_path, distance, elevation_gain,
               ST_Y(start_point) as lat, ST_X(start_point) as lng
        FROM routes WHERE id = %s
    """, (route_id,))
    route = cur.fetchone()
    if not route:
        print(f"Route {route_id} not found")
        return None

    # 현재 태그
    cur.execute("""
        SELECT t.slug FROM tags t
        JOIN route_tags rt ON rt.tag_id = t.id
        WHERE rt.route_id = %s ORDER BY t.slug
    """, (route_id,))
    current_tags = [r["slug"] for r in cur.fetchall()]

    print(f"=== Route #{route_id}: {route['title']} ===")
    print(f"  거리: {route['distance']/1000:.1f}km / 획득고도: {route['elevation_gain']}m")
    print(f"  현재 태그: {current_tags or '(없음)'}")
    print(f"  현재 설명: {route['description'] or '(없음)'}")

    # Load route JSON
    json_path = os.path.join(STORAGE_DIR, route['data_file_path'])
    if not os.path.exists(json_path):
        print(f"  ❌ JSON 파일 없음: {json_path}")
        return None

    with open(json_path, 'r') as f:
        full_data = json.load(f)

    # POI 정보 (디버그용)
    route_wkt = _build_route_line_wkt(full_data)
    route_pois = _get_waypoints_along_route(conn, route_wkt, radius_m=500) if route_wkt else []
    cp = _extract_control_points(full_data)
    cp_pois = _get_waypoints_near_control_points(conn, cp, radius_m=200) if cp else []

    print(f"  경로 POI: {len(route_pois)}개 / CP POI: {len(cp_pois)}개")

    # Gemini 생성
    print(f"  Gemini 생성 중...")
    result = generate_tags_and_description(conn, full_data)

    # 기존 태그와 매칭
    existing_tags = set(get_existing_tags(conn))
    matched_tags = [t for t in result["tags"] if t in existing_tags]
    new_tags = [t for t in result["tags"] if t not in existing_tags]

    print(f"  → 태그: {result['tags']}")
    print(f"    기존 매칭: {matched_tags}")
    print(f"    신규 제안: {new_tags}")
    print(f"  → 설명: {result['description']}")

    cur.close()

    return {
        "route_id": route["id"],
        "route_uuid": str(route["uuid"]),
        "title": route["title"],
        "current_tags": current_tags,
        "current_description": route["description"],
        "generated_tags": result["tags"],
        "matched_tags": matched_tags,
        "new_tags": new_tags,
        "generated_description": result["description"],
        "nearby_pois": [
            {"name": p["name"], "type": p["type"], "distance_m": p["distance_m"], "priority": p["priority"]}
            for p in (cp_pois + [p for p in route_pois if p["id"] not in {cp["id"] for cp in cp_pois}])
        ],
    }


def generate_sql(results: list[dict]) -> str:
    """DB insert/update용 SQL 생성."""
    lines = [
        "-- 자동 생성된 태그/설명 적용 SQL",
        "-- generated by: python scripts/test_auto_tag.py",
        "BEGIN;",
        "",
    ]

    all_new_tags = set()
    for r in results:
        all_new_tags.update(r["new_tags"])

    # 신규 태그 INSERT
    if all_new_tags:
        lines.append("-- 신규 태그 생성")
        for tag in sorted(all_new_tags):
            names_json = json.dumps({"ko": tag, "en": tag}, ensure_ascii=False)
            lines.append(
                f"INSERT INTO tags (names, slug) VALUES ('{names_json}', '{tag}') "
                f"ON CONFLICT (slug) DO NOTHING;"
            )
        lines.append("")

    # 루트별 태그 연결 + 설명 업데이트
    for r in results:
        route_id = r["route_id"]
        lines.append(f"-- Route #{route_id}: {r['title']}")

        # 설명 업데이트
        desc = r["generated_description"].replace("'", "''")
        lines.append(f"UPDATE routes SET description = '{desc}' WHERE id = {route_id};")

        # 기존 태그 제거 후 재연결
        lines.append(f"DELETE FROM route_tags WHERE route_id = {route_id};")
        for tag in r["generated_tags"]:
            tag_escaped = tag.replace("'", "''")
            lines.append(
                f"INSERT INTO route_tags (route_id, tag_id) "
                f"SELECT {route_id}, id FROM tags WHERE slug = '{tag_escaped}' "
                f"ON CONFLICT DO NOTHING;"
            )
        lines.append("")

    lines.append("COMMIT;")
    return "\n".join(lines)


def apply_to_db(conn, results: list[dict]):
    """생성 결과를 DB에 직접 적용."""
    sql = generate_sql(results)
    cur = conn.cursor()
    cur.execute(sql)
    conn.commit()
    cur.close()
    print(f"\n✅ DB 적용 완료 ({len(results)}개 루트)")


def main():
    args = sys.argv[1:]
    apply_mode = False

    if "--apply" in args:
        apply_mode = True
        args.remove("--apply")

    if not args:
        print("Usage: python scripts/test_auto_tag.py [--apply] <route_id> [route_id ...]")
        sys.exit(1)

    route_ids = [int(a) for a in args]

    conn = psycopg2.connect(**DB_CONFIG, cursor_factory=RealDictCursor)
    results = []

    for rid in route_ids:
        try:
            r = process_route(conn, rid)
            if r:
                results.append(r)
            print()
        except Exception as e:
            print(f"  ❌ Error: {e}\n")

    if not results:
        conn.close()
        return

    # JSON 결과 저장
    out_json = os.path.join(os.path.dirname(__file__), "output", "auto_tag_results.json")
    os.makedirs(os.path.dirname(out_json), exist_ok=True)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"📄 JSON: {out_json}")

    # SQL 생성
    sql = generate_sql(results)
    out_sql = os.path.join(os.path.dirname(__file__), "output", "auto_tag_apply.sql")
    with open(out_sql, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"📄 SQL:  {out_sql}")

    # --apply 모드
    if apply_mode:
        apply_to_db(conn, results)

    conn.close()


if __name__ == "__main__":
    main()
